
// This file has been generated by the GUI designer. Do not modify.
namespace HollyLibrary
{
	public partial class HDateEdit
	{
		private global::HollyLibrary.HBaseComboBox comboBox;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget HollyLibrary.HDateEdit
			global::Stetic.BinContainer.Attach (this);
			this.Name = "HollyLibrary.HDateEdit";
			// Container child HollyLibrary.HDateEdit.Gtk.Container+ContainerChild
			this.comboBox = new global::HollyLibrary.HBaseComboBox ();
			this.comboBox.Events = ((global::Gdk.EventMask)(256));
			this.comboBox.Name = "comboBox";
			this.Add (this.comboBox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
		}
	}
}
