
// This file has been generated by the GUI designer. Do not modify.
namespace HollyLibrary
{
	public partial class DateEditDialog
	{
		private global::Gtk.HBox hbox1;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Calendar CCalendar;
		private global::Gtk.HBox hbox2;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Label label4;
		private global::Gtk.SpinButton TxtHour;
		private global::Gtk.Label label2;
		private global::Gtk.SpinButton TxtMin;
		private global::Gtk.Label label3;
		private global::Gtk.SpinButton TxtSec;
		private global::Gtk.Button BtnClear;
		private global::Gtk.VBox vbox3;
		private global::HollyLibrary.AnalogClock Clock;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget HollyLibrary.DateEditDialog
			this.Name = "HollyLibrary.DateEditDialog";
			this.Title = "DateEditDialog";
			this.TypeHint = ((global::Gdk.WindowTypeHint)(2));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(1));
			this.Resizable = false;
			this.AllowGrow = false;
			this.Decorated = false;
			this.DestroyWithParent = true;
			this.SkipPagerHint = true;
			this.SkipTaskbarHint = true;
			// Container child HollyLibrary.DateEditDialog.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.BorderWidth = ((uint)(3));
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.CCalendar = new global::Gtk.Calendar ();
			this.CCalendar.CanFocus = true;
			this.CCalendar.Name = "CCalendar";
			this.CCalendar.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(3));
			this.vbox2.Add (this.CCalendar);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.CCalendar]));
			w1.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Homogeneous = true;
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = "H:";
			this.hbox3.Add (this.label4);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label4]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.TxtHour = new global::Gtk.SpinButton (0, 24, 1);
			this.TxtHour.CanFocus = true;
			this.TxtHour.Name = "TxtHour";
			this.TxtHour.Adjustment.PageIncrement = 1;
			this.TxtHour.ClimbRate = 1;
			this.TxtHour.Numeric = true;
			this.hbox3.Add (this.TxtHour);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.TxtHour]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = "M:";
			this.hbox3.Add (this.label2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label2]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.TxtMin = new global::Gtk.SpinButton (0, 60, 1);
			this.TxtMin.CanFocus = true;
			this.TxtMin.Name = "TxtMin";
			this.TxtMin.Adjustment.PageIncrement = 10;
			this.TxtMin.ClimbRate = 1;
			this.TxtMin.Numeric = true;
			this.hbox3.Add (this.TxtMin);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.TxtMin]));
			w5.Position = 3;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = "S:";
			this.hbox3.Add (this.label3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label3]));
			w6.Position = 4;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.TxtSec = new global::Gtk.SpinButton (0, 60, 1);
			this.TxtSec.CanFocus = true;
			this.TxtSec.Name = "TxtSec";
			this.TxtSec.Adjustment.PageIncrement = 10;
			this.TxtSec.ClimbRate = 1;
			this.TxtSec.Numeric = true;
			this.hbox3.Add (this.TxtSec);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.TxtSec]));
			w7.Position = 5;
			w7.Expand = false;
			w7.Fill = false;
			this.hbox2.Add (this.hbox3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.hbox3]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.BtnClear = new global::Gtk.Button ();
			this.BtnClear.CanFocus = true;
			this.BtnClear.Name = "BtnClear";
			this.BtnClear.UseUnderline = true;
			// Container child BtnClear.Gtk.Container+ContainerChild
			global::Gtk.Alignment w10 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w11 = new global::Gtk.HBox ();
			w11.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w12 = new global::Gtk.Image ();
			w12.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-clear", global::Gtk.IconSize.Menu);
			w11.Add (w12);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w14 = new global::Gtk.Label ();
			w14.LabelProp = "Now";
			w14.UseUnderline = true;
			w11.Add (w14);
			w10.Add (w11);
			this.BtnClear.Add (w10);
			this.vbox2.Add (this.BtnClear);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.BtnClear]));
			w18.PackType = ((global::Gtk.PackType)(1));
			w18.Position = 2;
			w18.Expand = false;
			w18.Fill = false;
			this.hbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.Clock = new global::HollyLibrary.AnalogClock ();
			this.Clock.WidthRequest = 254;
			this.Clock.Name = "Clock";
			this.Clock.Datetime = new global::System.DateTime (0);
			this.vbox3.Add (this.Clock);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.Clock]));
			w20.Position = 0;
			this.hbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 521;
			this.DefaultHeight = 263;
			this.Show ();
			this.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnButtonPressEvent);
			this.CCalendar.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnCalendar4ButtonPressEvent);
			this.CCalendar.DaySelected += new global::System.EventHandler (this.OnCCalendarDaySelected);
			this.CCalendar.DaySelectedDoubleClick += new global::System.EventHandler (this.OnCCalendarDaySelectedDoubleClick);
			this.TxtHour.ValueChanged += new global::System.EventHandler (this.OnTxtHourValueChanged);
			this.TxtHour.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnTxtHourButtonPressEvent);
			this.TxtMin.ValueChanged += new global::System.EventHandler (this.OnTxtMinValueChanged);
			this.TxtMin.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnTxtMinButtonPressEvent);
			this.TxtSec.ValueChanged += new global::System.EventHandler (this.OnTxtSecValueChanged);
			this.TxtSec.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnTxtSecButtonPressEvent);
			this.BtnClear.Clicked += new global::System.EventHandler (this.OnBtnClearClicked);
		}
	}
}
